version: '3.1'

services:

    testdb:
      image: mariadb
      container_name: testdb
      restart: always
      ports:
        - '3306:3306'
      environment:
        MARIADB_ROOT_PASSWORD: qwer12#$$
        MARIADB_DATADABSE: testdb
        MARIADB_USER: user
        MARIADB_PASSWORD: qwer12#$$
      volumes:
        - ./initdata1:/docker-entrypoint-initdb.d
        - ./testdb:/var/lib/mysql

    vaultdb:
      image: mariadb
      container_name: vaultdb
      restart: always
      ports:
        - '3307:3306'
      environment:
        MARIADB_ROOT_PASSWORD: qwer12#$$
        MARIADB_DATADABSE: vaultdb
        MARIADB_USER: user
        MARIADB_PASSWORD: qwer12#$$
      volumes:
        - ./initdata2:/docker-entrypoint-initdb.d
        - ./vaultdb:/var/lib/mysql
