version: '3.1'

services:

    db:
      image: mariadb
      container_name: testdb
      restart: always
      ports:
        - '3306:3306'
      environment:
        MARIADB_ROOT_PASSWORD: qwer12#$$
        MARIADB_DATADABSE: testdb
        MARIADB_USER: user
        MARIADB_PASSWORD: qwer12#$$
      volumes:
        - ./initdata:/docker-entrypoint-initdb.d
